### ISSUE TITLE
Export TSM AppData.lua information to CSV file.

### ISSUE THREAD

**Issue by xagonyx** [kamoo1/TSM-Backend#36]
Hello! Is it possible to export TSM AppData.lua information to a CSV file using this tool? If not, could you add it as a feature?

**Comment by kamoo1** [comment]
Sorry for the late reply,

Exporting to CSV does not fit the scope of this project, however it's not difficult to implement from what we have. 

You can start from `tsm_exporter.py` to understand the format of `AppData.lua` (its fields are numbers in base 32)
https://github.com/kamoo1/TSM-Backend/blob/2638bb5439670d93d1adc262a7659f87992a26ff/ah/tsm_exporter.py

From here you can do CSV either by adding it as an option when exporting or create a converter that reads the lua data.
